### ISSUE TITLE
Broken link in the readme

### ISSUE THREAD

**Issue by KennethEnevoldsen** [hauselin/ollama-r#25]
It seems like the link in the readme is broken:

> Download and install [Ollama](https://ollama.com/).

Assuming it is just a pip install it might be ideal to simply add the description instead of referring the user

**Comment by hauselin** [comment]
That's odd. When you click on it, does it not link to https://ollama.com/ (Ollama's home page)? I can update the README so the installation instructions are clearer for different OS. (and thanks for reviewing it!)

**Comment by hauselin** [comment]
Revised the link and installation instructions:

https://github.com/hauselin/ollama-r/blob/8bf8722d067bc102ec9eedec7a8f2188d4c2be05/README.md?plain=1#L68-L86

**Comment by KennethEnevoldsen** [comment]
> When you click on it, does it not link to https://ollama.com/ (Ollama's home page)?

Oh link works now. They website must have been down for a short while.

The new updated look great. Thought it was simply a pip install.
