### ISSUE TITLE
How to set the baseURL in Ollama-r?

### ISSUE THREAD

**Issue by slackmodel** [hauselin/ollama-r#28]
Hello,

I'm currently using Ollama and I have a question about setting a custom baseURL. Instead of using the default address http://localhost:11434/, I want to use a custom IP address like http://xxx.xxx.xxx.xxx:11434/.

Could you please provide guidance on how to configure a custom baseURL in Ollama?

I'm looking to change the default localhost address to a custom IP address. Is this possible, and if so, what are the steps to achieve this?

I would greatly appreciate any detailed documentation or guides on how to set a custom baseURL in Ollama.

Thank you for your help!

**Comment by hauselin** [comment]
All functions have a `host` parameter that defaults to NULL. Change it to your url. Refer to the documentation for your particular function [here](https://hauselin.github.io/ollama-r/reference/index.html).
