### ISSUE TITLE
`test_connection()` returns different type of object, depending on whether ollama server is running.

### ISSUE THREAD

**Issue by otoomet** [hauselin/ollama-r#29]
When the server is running, I get
````
> test_connection()
Ollama local server running
<httr2_response>
GET http://localhost:11434/
Status: 200 OK
Content-Type: text/plain
Body: In memory (17 bytes)
````
Note: this is a _httr2_response_ object

When the server is not running, I get
````
> test_connection()
Ollama local server not running or wrong server.
Download and launch Ollama app to run the server. Visit https://ollama.com or https://github.com/ollama/ollama
<httr2_request>
GET http://localhost:11434
Body: empty
````
Note: this is _httr2_request_ object.

The documentation states that:
````
Value
    A httr2 response object.
````

I'd expect the function to return an object of the same class in both cases, and the documentation to match the behavior.

A related note: it would be great to add another function, or maybe an argument (e.g. logical = TRUE), so that the function would return TRUE/FALSE.  This would simplify testing in the code whether the server is running.  Even if the result would correspond to the documentation, I need to test it using _httr2_ functionality, which is (slightly) more complex.  There could also be another option (eg quietly = TRUE) to suppress the messages on screen.

**Comment by hauselin** [comment]
Thanks for the suggestion! I'll take a look and implement in the next version!

**Comment by hauselin** [comment]
The function now returns boolean instead of httr2_response object.

**Comment by otoomet** [comment]
Thanks :-)

Will take a look when back at my work computer!

**Comment by hauselin** [comment]
I actually made a few changes so as to not break other packages that rely on ollamar. All the changes should address your issues above. See https://hauselin.github.io/ollama-r/reference/test_connection.html
