### ISSUE TITLE
Tool Calling Example Request

### ISSUE THREAD

**Issue by keshovsharma** [hauselin/ollama-r#30]
Love the library! One issue that I'm getting is that I cannot figure out how to format the list for tool calling. I've tried a couple different ways, but keep getting a 400 error. Instead of trying to debug my individual issue, I was wondering if you could provide a code snippet/reproducible example of successful tool calling somewhere in the docs? Best case scenario, can you reproduce the example from the Ollama Python library (https://github.com/ollama/ollama-python/blob/main/examples/tools.py)?

**Comment by hauselin** [comment]
Yes, will look into/work on this in the next few days!

**Comment by keshovsharma** [comment]
I was able to get the generate endpoint to produce structured JSON responses by passing the exported JSON schema of a pydantic model as a "format" parameter. I'm guessing that getting JSONs describing R functions should work just fine for tool calling, but I'm unaware of packages or methods for passing existing R functions to tool calling. Greatly appreciate anything inroads you can make here!

**Comment by hauselin** [comment]
Let me know if this works for you. I've tested and it seems to work. If so, I'll integrate into the library so it's easier to get the tool_calls from the response.

```r
library(ollamar)
library(httr2)

add_two_numbers <- function(x, y) {
    return(x + y)
}

msg <- create_message("what is three plus one?")

resp <- chat("llama3.1", messages = msg, output = "resp", 
          tools = list(list(type = "function", 
                       "function" = list(
                           name = "add_two_numbers",
                           description = "add two numbers",
                           parameters = list(
                               type = "object",
                               required = list("x", "y"),
                               properties = list(
                                   x = list(class = "numeric", description = "first number"),
                                   y = list(class = "numeric", description = "second number")
                                   )
                               )
                           )
                       )
                       )
          )
resp

resp_body <- resp_body_json(resp)
func <- resp_body$message$tool_calls[[1]]

func
func_name <- func$`function`$name
func_arguments <- func$`function`$arguments
func_arguments

do.call(func_name, func_arguments)

```

**Comment by hauselin** [comment]
See [advanced usage](https://hauselin.github.io/ollama-r/articles/ollamar.html#advanced-usage) for more examples.
