### ISSUE TITLE
chat() function

### ISSUE THREAD

**Issue by asaficontact** [hauselin/ollama-r#7]
For the following function, do: 
- [x] Implement the function if it is not already added
- [x] Refactor function if necessary
- [x] Compare the parameters against Ollama and Ollama-Python
- [x] Write documentation for the function 
- [x] Write tests for the function (follow conventions/tests [here](https://github.com/hauselin/ollama-r/blob/main/tests/testthat/test-test_generate.R)) and test with `testthat::test()`

See [`generate()` function](https://github.com/hauselin/ollama-r/blob/main/tests/testthat/test-test_generate.R) for template. `generate()` is a complete function with all features and has passed all tests.

**Comment by asaficontact** [comment]
Done with most of the tests, compare the parameters, and then finalize any additional tests that need to be added, then we are good to go with the function.

**Comment by hauselin** [comment]
Function needs refactoring and additional testing. See `generate()` function for examples and also see edits above^^
